name: TF AWS Test

on:
  workflow_dispatch:
    inputs:
      cmd:
        type: choice
        description: terraform command
        default: plan
        options:
          - plan
          - apply
      region:
        type: choice
        description: target region
        default: us-east-2
        options:
          - us-west-1
          - us-west-2
          - us-east-1
          - us-east-2
      vm_type:
        description: ec2 instance type
        default: t2.micro

env:
  AWS_ACCESS_KEY_ID:      ${{ secrets.ACCESS_KEY_STAGING }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.SECRET_KEY_STAGING }}
  AWS_REGION:             ${{ github.event.inputs.region }}
  #TF_ACTION_WORKING_DIR:  terraform

  # Terraform input variables
  inp_cmd:    ${{ github.event.inputs.cmd }}
  inp_region: ${{ github.event.inputs.region }}
  inp_vmtype: ${{ github.event.inputs.vmtype }}

jobs:

  build:
    runs-on: ubuntu-latest
    name: ${{ github.actor }} - perform tf ${{ github.event.inputs.cmd }}
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform Run
        run: |
          echo "** Start"
          SECONDS=0

          cd terraform
          cat << EOF > terraform.tfvars 
            region      = "$inp_region"
            vm_type     = "$inp_vmtype"
          EOF

          # terraform fmt -check

          echo "** TF Init"
          terraform init

          echo "** TF Validate"
          terraform validate -no-color

          [[ "$inp_cmd" == "plan" ]] && \
              echo "** TF Plan" && \
              terraform plan -no-color
          
          [[ "$inp_cmd" == "apply" ]] && \
              echo "** TF Apply" && \
              terraform apply -auto-approve -input=false
          
          echo "** Finish"
          echo "$(($SECONDS / 60)) min $(($SECONDS % 60)) sec elapsed"
        